sudo: required
services:
  - docker

before_install:
  - docker build -t flast1k/docker-react -f Dockerfile.dev .

script:
  - docker run flast1k/docker-react npm run test -- --watchAll=false --coverage

deploy:
  provider: Heroku
  api_key:
    secure: $HEROKU_ACCESS_KEY
  app: docker-react-project
  on:
    branch: master
